### ISSUE TITLE
RemoteComponent is incompatible with the newest version of Knit

### ISSUE THREAD

**Issue by LuaBrowser** [EncodedVenom/RemoteComponent#2]
The RemoteComponent Utility is incompatible due to changes with how communication is handle, with both the Remote Signal and Remote Property modules being phased out, leaving a single Communications module.

**Comment by EncodedVenom** [comment]
Was holding off because I wasn’t sure how Wally was going to be integrated with Knit. Will implement a Wally pkg or similar to fix this.

**Comment by LuaBrowser** [comment]
For clwrification, the issue seems to be with using the exposed ``Is`` RemoteSignal function, of which said util has been removed from my understanding.

**Comment by EncodedVenom** [comment]
There is now a Wally package (encodedvenom/remotecomponent@0.1.0-rc.2) which solves this issue.
