### ISSUE TITLE
[Wally] TableUtil.CopyShallow no longer exists, but is used

### ISSUE THREAD

**Issue by Synthetic-Dev** [EncodedVenom/RemoteComponent#3]
Hey, using RemoteComponent for a new project of mine. It seems that TableUtil has had the `:CopyShallow()` method removed from it, which RemoteComponent still uses in the `:GetAll()` method. It seems to have changed to a `:Copy(table, deep)` format.

Just informing you so that you are able to change it.

**Comment by EncodedVenom** [comment]
Thanks for letting me know. I've fixed this in the latest wally patch and will be pushing to the github page in a moment.
